### ISSUE TITLE
Vereinsübernahme

### ISSUE THREAD

**Issue by fabianhauser** [openhsr/verein#1]
Der aktuelle Vorstand des Vereins ist nicht mehr an der HSR. Die Vorstandsmitglieder freuen sich aber, wenn der Verein weitergeführt wird!

Dafür sind ein paar Schritte nötig:
- [x] Mitgliederliste aktualisieren
  - Zwei Mitglieder  haben noch eine aktive HSR E-Mail-Adresse
  - Drei Mitglieder sind nicht mehr an der HSR, aber noch aktiv (Vorstand)
- [x] Neuer Vorstand stellen
  - **Kassierin**: @tarinya 
  - **Aktuar**: @olidias 
  - **Beisitz / Chief Website**: @michiwieland 
  - **Vize / Chief Support**: @raphiz 
  - **Präsident**: @fabianhauser
- [x] GV organisieren und Vorstand wählen lassen: Siehe #3 
- [x] Mailbox übernehmen
- [x] Vereinskonto übernehmen (vermutlich bei der Bank Linth)
- [x] Twitter Account übernehmen (Anfrage an [Odi](https://twitter.com/odi) @fabianhauser 20160403, Anfrage Twitter 20160420)

@fabianhauser hat vom alten Vorstand folgende Unterlagen erhalten:
- E-Mail Login
- Webspace FTP-Login
- Mitgliederliste
- Statuten-Tex-Source (ist in diesem Repo abgelegt)
- Ein paar alte Präsentationen / Plakate

**Comment by raphiz** [comment]
@fabianhauser hast du etwas bezüglich dem Twitter Account gehört?

**Comment by fabianhauser** [comment]
@raphiz : Leider nicht. Beim versuchten Passwort-Reset sagt mir Twitter, dass das Login auf `so******@h**.**` lautet: gibt es nicht mehr. Habe deshalb mal eine Support-Anfrage bei Twitter zur Änderung der E-Mail gestartet (_"usually able to respond within a few days"_, we'll see.)

**Comment by fabianhauser** [comment]
Bisher ist leider kein Feedback betreffend Twitter-Account eingetroffen, habe nochmal bei Odi nachgefragt und vorübergehend den Twitter-Button von der Webseite entfernt.

**Comment by fabianhauser** [comment]
Wegen dem Twitter Account: Sieht nicht so aus, als könnten wir zugriff darauf erhalten. Falls wir ein Rebranding machen, erübrigt sich das sowieso; habe die Checkbox darum mal gechecked.

**Comment by fabianhauser** [comment]
Ich habe für die Übernahme des Vereinskontos mal ein eigenes Issue #9 erstellt. Damit kann dieses Issue geschlossen werden.
