### ISSUE TITLE
Sponsoring 2016 abklären

### ISSUE THREAD

**Issue by fabianhauser** [openhsr/verein#10]
Abklären betreffend einem Sponsoring für das [aktuelle Jahresbudget](https://github.com/altcomphsr/verein/blob/master/protokolle/2016/05_generalversammlung/protokoll.md#budget-2016). In Frage käme die Unterstützung vom VSHSR sowie einem an Open Source interessierten Geschäft.

**Comment by fabianhauser** [comment]
@murieleTrentini: Schauen wir bei Gelegenheit mal an, wie wir bei diesem Issue vorgehen?

**Comment by murieletrentini** [comment]
tiptop. Machen wir einen termin.

**Comment by fabianhauser** [comment]
Dank dem grossartigen Einsatz von @michiwieland konnten wir die [CalandaComp](http://calandacomp.ch/) aus Landquart als Sponsor von CHF 200.- gewinnen. Damit sind alle Geldsorgen für das aktuelle Vereinsjahr gelöst :smiley: 

Dieses Issue kann somit geschlossen werden.

**Comment by raphiz** [comment]
@fabianhauser Wir dürfen aber nicht vergessen, dass wir ensprechend das Logo auf die Website?

**Comment by fabianhauser** [comment]
@raphiz: Das hatte ich geistig schon abgehakt :blush:
@michiwieland: Könntest du das Logo noch einfügen?

**Comment by michiwieland** [comment]
Ich schlage vor, wir machen eine Subseite "Sponsoren&Supporter" unter Community und listen dort die verschiedenen Organisationen mit ihrem Logo auf. Gleichzeitig könnte dort auch dr VSHSR als "Eltern-Verein" sowie der Codedump genannt werden. (falls wir mit diesen in Zukunft zusammentun). Was meint ihr?

**Comment by fabianhauser** [comment]
Mein Vorschlag wäre, die Logos auf der Startseite unter den Blauen Blöcken<sup>TM</sup> nebeneinander aufzulisten. So sparen wir uns eine eigene Seite :)

**Comment by raphiz** [comment]
Können wir das Ticket zumachen?
