### ISSUE TITLE
Öffnen der Github-Organisation für alle Mitglieder

### ISSUE THREAD

**Issue by raphiz** [openhsr/verein#12]
Würde gerne mal die Disukussion anstiften, ob und wie alle Mitglieder bei der Organisation mitwirken können (Ich finde, ja gerne 😉 ).

Vorteile davon wären bsp. dass sich Mitlgieder selber Issues zuweisen und erledigen können.

Ich würde mir dafür aber ein "Merge-Komitee" wünschen, welche die Hoheit hat, was auf den Master-Branch kommt und somit auf die Website (oder in Connect usw.).

@openhsr/vorstand Was habt ihr für Vorstellungen davon?

**Comment by fabianhauser** [comment]
Also grundsätzlich ist es ja jetzt schon möglich, sich an den Issues zu beteiligen und Pull-Requests zu machen.  
Aber ich fände es auch gut, alle Mitglieder (die möchten) in das GitHub-Projekt aufzunehmen. Falls sich jemand in einem bestimmten Repository engagiert, könnten wir ja entsprechende Arbeitsgruppen anlegen, z.B. `website`, `connect`, über welche die Zugriffsrechte gesteuert werden.

**Comment by michiwieland** [comment]
Ich schliesse mich ganz eurer Meinung an. Finde auch, dass wir das Projekt grundsätzlich jedem öffnen sollten, jedoch immer noch die Kontrolle über die Pull-Request behalten.

**Comment by raphiz** [comment]
Alle Mitglieder dürfen also in die Organisation - der Zugriff auf den Master-Branch ist aber gesperrt. Auf den Master-Branch darf nur der Vorstand und Mitglieder nach Bedarf und Nachfrage pushen.

@openhsr/vorstand passt das so?

**Comment by fabianhauser** [comment]
@raphiz Ja das ist meiner Meinung nach gut so; alle Mitglieder die möchten, werden einfach in die Organisation aufgenommen. Ein weiterer Zugriff auf ein Repo kann ja allenfalls nach Bedarf entschieden werden.
Habe Nikola schon mal eingeladen :smiley:
