### ISSUE TITLE
OpenHSR Stickers!

### ISSUE THREAD

**Issue by raphiz** [openhsr/verein#14]
Ich hätte gerne eine Open\HSR Sticker auf dem Notebook...wäre eigentlich ein nettes "Willkommensgeschenk" für neue Mitglieder (und natürlich für die bisherigen 😉 )

Preislich müssen wir je nach Qualität mit 1-2 CHF pro Sticker rechnen...

Habt ihr auch Interesse?

**Comment by fabianhauser** [comment]
Finde ich eine super Idee! So günstige Werbefläche ist schwierig zu finden :wink:

**Comment by raphiz** [comment]
Stickers sind bestellt

**Comment by raphiz** [comment]
Die Stickers werden voraussichtlich ab dem 17. Oktober endlich da sein!

**Comment by fabianhauser** [comment]
Die Stickers sind angekommen und können bei @raphiz abgeholt werden! :tada:
