### ISSUE TITLE
Sponsoringvertrag aufsetzen

### ISSUE THREAD

**Issue by fabianhauser** [openhsr/verein#16]
Es soll ein kleiner Sponsoring-Vertrag aufgesetzt werden, gemäss den im Protokoll Vorstandssitzung 2016-07 #15 festgelegten Kategorien.

**Comment by murieletrentini** [comment]
[Sponsoringvertrag.pdf](https://github.com/openhsr/verein/files/423324/Sponsoringvertrag.pdf)
Hier einmal eine erste Fassung des Sponsering Vertrags mit Amétiq. Anregungen sind erwünscht.
Noch ein paar Punkte die wir klären sollten:
- Braucht es von unserer Seite zwei Unterschriften? Wie ist das in den Statuten geregelt?
- Soll drauf stehen, ab wann die vereinbarte Zahlung zu erfolgen hat?
- Soll drauf stehen, dass der Vertrag nicht kündbar ist wärend der Laufzeit von 1 Jahr?

**Comment by michiwieland** [comment]
Ich denke die wichtigsten Punkte sind abgedeckt und der Vertrag ist schon ziemlich gut. 
Vielleicht noch folgende Ideen:
- Der Beitrag ist als Vorrauszahlung zu entrichten.
- Weitere Kosten und Verpflichtungen sind ausgeschlossen.
- Vor Ablauf der Vertragsdauer liegt es beim Sponsoren ob er sich für ein weiteres Jahr verpflichten möchte. Wird dies nicht wahrgenommen, erlischt das Verhältnis automatisch.

**Comment by fabianhauser** [comment]
Gemäss Statuten:

> § 4.3.7 für finanzielle Belange gilt für den Präsidenten und den Vizepräsidenten die Kollektivunterschriftsberechtigung zu zweien, sowie für den Kassier Einzelunterschriftsberechtigung

Sprich, du kannst das gleich unterschreiben wenn du möchtest :wink: 

> Soll drauf stehen, dass der Vertrag nicht kündbar ist wärend der Laufzeit von 1 Jahr?

Wegen Kündigungen: Würde ich nur auf Vereinsjahresende mit einer Frist von 2 Monaten zulassen, sonst müssten wir theoretisch Flyer neu drucken etc.
Normalerweise läuft der Vertrag ja sowieso dann aus (das würde dann für längere Verträge gelten).

Allerdings wäre ein Ausschluss im Stil von _Beiträge für das aktuelle Vereinsjahr bleiben geschuldet und werden nicht zurückerstattet_ noch gut.

Ansonsten kann ich mich nur Michi anschliessen :)

**Comment by murieletrentini** [comment]
Habs mal überarbeitet. Wie findet ihrs?
Bin beim Begleitschreiben froh um Verbesserungsvorschläge. Das erscheint mir noch etwas holprig.
[Sponsoringvertrag.pdf](https://github.com/openhsr/verein/files/430051/Sponsoringvertrag.pdf)

**Comment by raphiz** [comment]
@murieletrentini Das Begleitschreiben könntest du von mir aus von dir als absender i.v. des open\HSR Vorstands senden. Damit wird es etwas persönlicher. 
Ist Sponsoringvertrag nicht ein Wort?

Sonst könnte man noch etwas kurz zum Kontext schreiben - also wer mit wem was vereibart hat - also warum dieses Schreiben überhaupt kommt (Sollte ja schon klar sein, aber falls es jemand anderes liest...)

Optional könnte man auch schreiben, dass der Flyer bereits draussen ist - könnte man auch einen beilegen.

**Comment by fabianhauser** [comment]
Ein (etwas weniger formeller) Briefvorschlag:

> Geschätzter Robert
> 
> Wir freuen uns sehr, euch als Sponsor begrüssen zu dürfen! Im Anhang findest du den unseren Sponsoringvertrag gemäss den Abmachungen per E-Mail. Wir wären froh, wenn du ein Exemplar unterschrieben wieder an uns returnieren könntest. Herzlichen Dank!
> 
> Im Anhang findest du zudem ein paar Exemplare unseres Flyer. Wir hoffen, er gefällt euch.
> 
> Wir freuen uns auf eine gute Zusammenarbeit!
> Beste Grüsse
> Der open\HSR Vorstand
> i.v. Muriele Trentini (Kassierin)

Dann wäre es gut, wenn es im Briefkopf noch deine Adresse hat, damit sie den Vertrag wieder retournieren können :smiley: 

Ansonsten:  :+1:

**Comment by murieletrentini** [comment]
Hier die endgültige Version. Wenn keine Einsprüche mehr kommen, werd ich den Vertrag Ende Woche abschicken.
[Sponsoringvertrag.pdf](https://github.com/openhsr/verein/files/444705/Sponsoringvertrag.pdf)

**Comment by fabianhauser** [comment]
@murieletrentini: Wenn du deine Adresse noch auf den Begleitbrief schreibst, damit sie den Vertrag wieder retournieren können, ist es perfekt :wink:

**Comment by murieletrentini** [comment]
ergänzt mit Absender und Bankverbindung
[Sponsoringvertrag.pdf](https://github.com/openhsr/verein/files/447394/Sponsoringvertrag.pdf)
