### ISSUE TITLE
Rebranding: open\HSR

### ISSUE THREAD

**Issue by raphiz** [openhsr/verein#2]
Das Vereinslogo, der Vereinsname und der (derzeit fehlende) "Slogan" brächten ein update auf das Jahr 2016.

Ideen und Vorschläge sind herzlich willkommen :wink:

**Comment by fabianhauser** [comment]
irgendwas mit _open_? :)

**Comment by fabianhauser** [comment]
An der GV 2016-05 wurde open\<sup>HSR</sup> als zukünftiger Vereinsname festgelegt. Daraus ergeben sich folgende Tasks:
- [x] Domain `openhsr.ch` reservieren
- [x] Twitter-Account `openhsr` anlegen
- [x] Github-Organisation umbennenen.  
  - [x] Reservieren des alten Namens mit Hinweis auf neuen.
- [x] Github Repository altcomphsr.vshsr.ch auf www.openhsr.ch umbenennen
- [x] Webseite und Mailbox auf die neue Domain zügeln
  - [x] Organisieren mit VSHSR
  - [x] Weiterleitungen einrichten
  - [x] FTP-Passwort ändern
- [x] Anpassen des Namens auf der Website
  - (Irgendwo klarstellen, warum der Verein ein Unterverein vom VSHSR ist bzw. was das für Vorteile mitbringt)
- [x] Logo / Icon erstellen
- [x] Anpassen Nennung vom Verein auf der VSHSR-Website
- [x] IRC-Channel
- [x] Namen anpassen in den Statuten

**Comment by fabianhauser** [comment]
Hallo @openhsr/vorstand 

Ich habe die GitHub-Organisation zu `openhsr` umbenannt. Damit eure lokalen Git-Repositories wieder an den richtigen Ort pushen, könnt ihr in allen Repositories folgenden Befehl ausführen:

``` bash
cd verein # etc.
sed -i 's/altcomphsr\//openhsr\//gi' .git/config
```

Falls was nicht funktionieren sollte, einfach Bescheid geben. Ich passe gleich noch die Webseite mit den neuen Links an.

**Comment by raphiz** [comment]
btw. die links sind nicht kaputt gegangen... https://github.com/altcomphsr/* leitet auf https://github.com/openhsr/* weiter

**Comment by fabianhauser** [comment]
Habe ein E-Mail an Katharina vom VSHSR für die Anpassung der Domain und E-Mail gesendet.

**Comment by fabianhauser** [comment]
FYI @openhsr/vorstand: Die Webseite läuft unter der neuen Domain; das Deployment tut momentan allerdings nicht, irgendwas hat beim Umstellen des FTP-Logins nicht geklappt. Schaue das noch an.

**Comment by fabianhauser** [comment]
Hey @openhsr/vorstand 
Das Deployment der Webseite funktioniert wieder. Ich habe zudem das Webseiten-Repository auf www.openhsr.ch umbenannt.

**Comment by fabianhauser** [comment]
Text für den VSHSR:

> Du möchtest Open Source an der HSR fördern oder ein nicht offiziell unterstütztes Betriebssystem an der HSR nutzen (wie z.B. Linux oder Mac OS X)?
> Dann bist du bei uns richtig!
> 
> Als Mitglieder sind Studenten aller Fachrichtungen willkommen, unabhängig davon, ob du in die Open Source Welt einsteigen willst oder dich bereits auskennst.
> 
> Mehr Informationen zu uns sowie nützliche Anleitungen findest du auf unserer Webseite: [www.openhsr.ch](https://www.openhsr.ch/)

@openhsr/vorstand : Was haltet ihr davon? Der Text sollte neben der VSHSR-Webseite auch z.B. in einer gedruckten Vereinsübersicht genutzt werden können.

**Comment by raphiz** [comment]
@fabianhauser für mich perfekt 👍

**Comment by michiwieland** [comment]
Könnte nicht besser sein. Informiert und macht Lust auf mehr

**Comment by raphiz** [comment]
Nochmals kurz hier was noch fehlt:
- [x]  Anpassen Nennung vom Verein auf der VSHSR-Website
- [ ]  Rundmail an alle.

Dann können wir das zumachen

**Comment by fabianhauser** [comment]
Das Mail mit dem Logo und neuen Text für die VSHSR Webseite wurde versendet.

**Comment by raphiz** [comment]
User Eintrag auf der VSHSR Website ist nun auch angepasst - Merci @fabianhauser !
