### ISSUE TITLE
Git/Github Workshop organisieren

### ISSUE THREAD

**Issue by raphiz** [openhsr/verein#20]
Habe mal einen ersten Entwurf eines Konzepts entworfen und eingecheckt (https://github.com/openhsr/git-github-workshop/blob/master/notes/00-overview.md)

Was haltet ihr davon?

**Comment by olidias** [comment]
Sehr einladend! Denke, dass definitiv Interesse da ist.. Auf jeden Fall von meiner Seite :+1:

**Comment by raphiz** [comment]
Wurde erfolgreich mit ca. 30 Teilnehmern durchgeführt.
Siehe https://github.com/openhsr/git-github-workshop/
