### ISSUE TITLE
Third-Party application restrictions auf GitHub einschalten

### ISSUE THREAD

**Issue by The-Compiler** [openhsr/verein#22]
Momentan können alle Applikationen (à la Travis CI und so) die openhsr-Member für ihren GitHub account zulassen auch auf die openhsr-Repos zugreifen.

Dies lässt sich [umschalten](https://help.github.com/articles/enabling-third-party-application-restrictions-for-your-organization/), was inzwischen afaik auch das default ist.

Wobei:

> Enabling third-party application restrictions will revoke organization access for all previously authorized applications **and SSH keys**.

Aber ist IMHO trotzdem sinnvoll.

**Comment by fabianhauser** [comment]
Vielen Dank für die Anregung @The-Compiler, habe das gleich entsprechend umgestellt!
(Der Zugriff für Travis-CI wurde wieder eingerichtet, das Webseiten Deployment sollte also funktionieren.)
LG Fabian
