### ISSUE TITLE
VPN-Verbindung ohne Cisco-Client

### ISSUE THREAD

**Issue by valioDOTch** [openhsr/verein#24]
Hat das schon jemand erfolgreich probiert?

An der Uni Basel hatten wir einen Ansatz mit vpn, sowie mit dem Client von OS X
http://fg-informatik.unibas.ch/wiki/index.php/WLAN_und_VPN_mit_vpnc
http://fg-informatik.unibas.ch/wiki/index.php/VPN_unter_Mac_OS_X_mit_systemeigenem_VPN-Client

Ich hab's nicht auf Anhieb geschafft.

**Comment by raphiz** [comment]
@valioDOTch bin mir nicht sicher, ob ich dich richtig verstanden habe, [auf der Website empfehlen wir genau diesen Weg](https://www.openhsr.ch/hsr/vpn/)
Gibt es damit auch Probleme?

**Comment by valioDOTch** [comment]
autsch; ich kann die Seite gar nicht ;-)
