### ISSUE TITLE
Übergabe Vorstand 2017

### ISSUE THREAD

**Issue by fabianhauser** [openhsr/verein#28]
- [x] Github (Vorstand)
- [x] Pass-Repository (Vorstand)
- [x] Vereinskonto (Präsident / Kassierin)
- [x] Papierunterlagen (Präsident)
- [x] Marketingmaterial und Stickers
- [x] Kontakte/Sponsoren informieren
- [x] <del>Anpassen Verträge</del>

## Neue Vorstandsmitglieder

- [x] E-Mail Postfach
- [x] Pass Repository

**Comment by raphiz** [comment]
-> https://github.com/openhsr/verein/tree/master/handbuch
