### ISSUE TITLE
GV Organisieren 2016-05

### ISSUE THREAD

**Issue by fabianhauser** [openhsr/verein#3]
Organisieren der GV zur Übernahme des Vereins gem. #1 
- [x] Traktanden
- [x] Datum
- [x] Ort
- [x] ...?

**Comment by raphiz** [comment]
Also, wenns nach mir geht kommen sicher folgende Traktanden ins Program:
- GV eröffnen durch den Präsident
- Wahl des Protokollführer und Stimmenzähler
- Neuwahlen (Vorstand,Revisoren)
- Abstimmung Neuausrichtung des Vereins (evtl. Statutenänderungen?)
- Besprechung Roadmap bis beginn HS16 (Flyer, Launch Website, Re-Branding)
- Weiteres Vorgehen übernahme des Vereinskontos
- GV schliessen durch Präsident

**Datum**: so bald wie möglich :) Am besten wir machen einen Doodle und tragen uns alle ein!
**Ort**: Je nach Wetter und Uhrzeit am See oder im Bären

**Comment by fabianhauser** [comment]
Klingt schon mal gut!

Eine Ergänzung: Alte, unbezahlte Mitglieder sind gemäss Statuten keine Mitglieder mehr und Aufnahme von neuen Mitgliedern :wink:

Ich denke es wäre von Vorteil, für die Neuausrichtung des Vereins bereits einigermassen konkrete Change-Requests dabeizuhaben. Werde das mal vorbereiten und die nächsten Tage (Morgen?) ein Doodle rauslassen.

**Comment by raphiz** [comment]
Habe mal geschaut was so Flyer kosten - wenn wir einen A6 Flyer doppelseitig drucken sollten wir 500 Exemplare unter 50 CHF bekommen (Bei flyerking, flyerline oder saxoprint). Alles was grösser ist - oder besseres Druckpapier macht die Sache halt teuer...
Ihr könnt ja auch mal nachschauen - ich finde, der Flyer muss ja nicht vergoldet sein aber Billig sollte er auch nicht wirken...

**Comment by fabianhauser** [comment]
Hallo lieber @altcomphsr/vorstand 

Könntet ihr [das Protokoll zur GV](https://github.com/altcomphsr/verein/blob/master/protokolle/2016/05_generalversammlung/protokoll.md) durchsehen und kurz ein Feedback geben, ob noch was angepasst werden müsste?

Danke & LG
Fabian

**Comment by raphiz** [comment]
Ich hätte noch 3 Änderungsvorschläge zum Protokoll:
- Theoretisch müssten wir ja auch den Aktuellen Vorstand erwähnen - oder irgendwie erwähnen, dass wir von ihnen eine vollmacht o.ä. erhalten haben .... 
- Dann weiss ich nicht, ob das möglich ist, wenn jemand entschuldigt abwesend ist trotzdem stimmberechtigt sein kann (da zeigt sich meine juristische Inkompetenz ) - für scheint das einfach ungewohnt...und ich hätte dafür einfach gesagt wir sagen war dabei oder Abwesend - dann auch ohne Stimmrecht... (Das kingt ja so, als wollte ich Stimmrechte einschränken und die Macht an mich reissen 😄)
- Dann noch eine Forlmuierung: `[...]Mergen von zukünftigen Pushes der [...]`  würde ich korrekterweise auf `[...]Mergen von zukünftigen Pullrequests der [...]`  umschreiben...

Sonst ist das Protokoll top! Merci @olidias

**Comment by fabianhauser** [comment]
Ja, @raphiz, hast du autokratische Ziele? Bin ja mal gespannt auf den nächsten Präsidentenwahlkampf :laughing: 

Aber mal ernsthaft:
- entweder jemand ist anwesend und kann abstimmen oder war abwesend, würde ich auch sagen.
- _Betreffend dem aktuellen Vorstand:_ Schreiben wir doch rein, dass mir der ehemalige Präsident (Danilo Bargen) eine Vollmacht für die Durchführung gegeben hat; er muss das Protokoll und die neuen Statuten so oder so noch unterschreiben (dafür könnten wir übrigens auch noch eine kleine Tabelle am Schluss einfügen:

| Präsident | Aktuar |
| --- | --- |
| Danilo Bargen | Raphael Nestler |
| &nbsp; | &nbsp; |

**Comment by raphiz** [comment]
@openhsr/vorstand können wir das zumachen? Ich glaube, das Protokoll können wir so absegnen 😺

**Comment by fabianhauser** [comment]
Das Protokoll passt auch aus meiner Sicht; ich würde das Issue aber gerne noch offen lassen, bis wir eine Signatur von @dbrgn und @rnestler haben. Werde mein Glück mal am Montag im Coredump versuchen :wink:

**Comment by dbrgn** [comment]
Sehr coole Sache das Ganze!

Ich kann euch gerne die Unterschrift geben! :) Kann noch nicht 100%ig sagen ob ich morgen im Coredump bin, aber wenn nicht dann sicher am 6. Juni.

Falls ihr interessiert daran seid, können wir auch gerne gegenseitig etwas Werbung füreinander machen.

**Comment by rnestler** [comment]
Ich erteile meine Unterschrift für alles was alt.comp.hsr / openhsr betrifft.

**Comment by fabianhauser** [comment]
@openhsr/vorstand: Wir haben im Protokoll noch ein paar Formulierungen verdeutlicht und jetzt eine unterschriebene Version vom Präsidenten und Aktuar. Somit können wir bei der Bank Linth betreffend dem Konto Kontakt aufnehmen!
