### ISSUE TITLE
Vereinsvorstellung HS2017 organisieren

### ISSUE THREAD

**Issue by InverseIntegral** [openhsr/verein#30]
**Datum**: Mittwoch, 4.10.2017 11.50-13.00 Uhr
**Aufstellen**: 11:30 Uhr

### Material
- Webhosting Gutscheine von Hostpoint
- Open\HSR Sticker
- Flyer
- Plakate
- Schöggeli

Falls Jemand mithelfen will bzw. noch Ideen für unseren Stand hat, meldet euch 😉

**Comment by fabianhauser** [comment]
Wir haben letztes Jahr zum "anlocken" noch Schöggeli verteilt 😉 

Wäre es für euch okay, wenn wir auch ein Studentenportal-Logo am Stand aufhängen? Dafür bräuchte es dringend ein paar aktive Entwickler...

**Comment by InverseIntegral** [comment]
Können wir gerne machen, habt ihr ein "offizielles" Logo oder reicht der Schriftzug mit entsprechender Schriftart und -farbe?

**Comment by fabianhauser** [comment]
Wir haben eine SVG-variante: https://github.com/studentenportal/web/blob/master/apps/front/static/img/studentenportal.svg

Merci!

**Comment by InverseIntegral** [comment]
Wir heissen drei neue Mitglieder in unserem Verein willkommen.
Vielen Dank an alle, die mitgeholfen und vorbeigeschaut haben.
