### ISSUE TITLE
Flyer für Studienstart HS18

### ISSUE THREAD

**Issue by InverseIntegral** [openhsr/verein#33]
Bis Ende Juni 2018 müssten ca. 480 Flyers gedruckt sein und bei den Hochschuldiensten abgegeben werden.

- [x] Design der Flyers überarbeiten
  - [x] QR-Code updaten
  - [x] Text verbessern
  - [x] Sponsoren entfernen
- [x] Druck abklären @SeboCode 
- [x] Hinzufügen der Sponsoren-Logos
- [x] Druck der neuen Flyers
- [x] Flyers zur HSR bringen

Falls sich Jemand mit Photoshop auskennt und mithelfen möchte, gerne melden!

**Comment by The-Compiler** [comment]
Was Druck angeht: Ich hab gute Erfahrungen mit [Flyeralarm](https://www.flyeralarm.com/ch/) gemacht, zumindest für Sticker. Die sind extrem günstig, und ich hab daheim noch ein Muster-Buch rumliegen mit verschiedenen Papiermaterialien.

**Comment by raphiz** [comment]
FYI: Das psd kann auch (für eine Notfalloperation am offenen Herzen) mit Gimp geöffnet und modifiziert werden. Dafür muss aber irgendwas mit dem Farbmodell angepasst werden... => http://www.openmutual.org/2011/08/converting-cmyk-psd-files-for-use-in-gimp/

Wäre sowieso nice, das ganze für Gimp, Inkscape oder so was zu migrieren - etwas was halt frei ist...

**Comment by SeboCode** [comment]
@The-Compiler Danke für den Tipp, ich werds mir anschauen.

**Comment by SeboCode** [comment]
@raphiz So wie ich den Blogpost verstanden habe, bekommt man durch das Tool nur die einzelnen Layers als .png zurück. Damit könnte man zwar schnell einen neuen Flyer zusammenklicken, jedoch würde ich raten, den Flyer komplett neu mit GIMP zu erstellen. Dies würde auch das Updaten in den kommenden Jahren vereinfachen. Ich habe den Header bereits erstellt, und finde er sieht recht ähnlich aus https://github.com/openhsr/verein/commit/cb7f69aa15007f5b985fde065b40051bedf78bc0

**Comment by raphiz** [comment]
Oh, stimmt, der Artikel beschreibt nicht explizit was ich ausprobiert habe :see_no_evil: 
Habe einfach als Output bei ImageMagick auch psd gewählt...Das ganze aber neu zu machen ist (sofern du zeit hast) aber natürlich top :+1: 

```
convert Welcom2HSR.psd channel RGBA -alpha Set -colorspace rgb output.psd
```

**Comment by SeboCode** [comment]
Das Konvertieren hat zwar funktioniert, jedoch hatte es einige Mühseligkeiten und Unschönheiten, weshalb ich ihn komplett neu erstellt habe. Ich wäre froh, wenn sich einige Leute das neue Template anschauen und im Pull Request #38 Feedback geben könnten 😄

**Comment by InverseIntegral** [comment]
Ich habe das Template mal gemergt. Sobald die Sponsoren bekannt sind, füge ich noch die Logos hinzu.

**Comment by InverseIntegral** [comment]
Insgesamt wird es 108 neue Informatikstudierende geben. Wollen wir nur diesen einen Flyer geben oder allen neuen Studierenden?

**Comment by fabianhauser** [comment]
Also ich persönlich fände es cool an alle, weil es auch immer ein paar interessierte aus anderen Studiengängen.

Aber braucht dann halt schon deutlich mehr Flyer, die Frage ist, ob euch das der Aufwand wert ist?

**Comment by The-Compiler** [comment]
Aufwand inwiefern? So wie das oben beschrieben war, muss man die ja nur bei den Hochschuldiensten abgeben?

Finanziell macht das praktisch keinen Unterschied - ob 100 oder 500 ist ne Sache von 5 CHF oder so. So kleine Mengen sind halt für Druckereien nix, und im Vergleich dementsprechend teuer.

**Comment by raphiz** [comment]
Ja, die Kosten sollten nicht entscheidend sein - ich würde mir einfach gut überlegen, wie prominent macOS auf dem Flyer steht - sonst müsst ihr für die ganze HSR mac support leisten...

**Comment by SeboCode** [comment]
Die Flyer können wir mit dem Geschäftsdrucker meines Vaters drucken. Somit würden fast keine Druckkosten entstehen.

**Comment by InverseIntegral** [comment]
Wir haben uns entschieden die Flyer an alle neuen Studierenden zu verteilen

**Comment by InverseIntegral** [comment]
Die Flyers sind gedruckt und werden morgen an der HSR abgegeben. Vielen Dank an @SeboCode für die Organisation des Drucks und das Erstellen des neuen Flyers!
