### ISSUE TITLE
Finanzdokumente in Repository ergänzen

### ISSUE THREAD

**Issue by fabianhauser** [openhsr/verein#35]
Es wäre cool, wenn das Budget etc. auch hier im Repository abgelegt würde.

Ausnahme sind Dokumente, welche persönliche Daten enthalten. Evtl. könnten diese verschlüsselt abgelegt werden.

**Comment by InverseIntegral** [comment]
Folgende Dokumente konnte ich finden: 

Rechnungen:
- [x] StickerMule
- [x] Git Workshop 2016
- [x] Codesprint 2016
- [x] Vereinsvorstellung 2016
- [x] Codesprint Februar 2017
- [x] GV 2017
- [x] Sponsoring Compass Security

Kontoauszüge:
- [ ] 10.06.2016 - 31.07.2016
- [ ] 01.08.2016 - 31.08.2016
- [ ] 01.09.2016 - 31.10.2016
- [ ] 01.11.2016 - 31.12.2016
- [ ] 01.01.2017 - 28.02.2017
- [ ] 01.03.2017 - 30.04.2017

Budget:
- [x] 2016
- [x] 2017
- [x] 2018

Sonstiges:
- [ ] Kundenbrief mit Basisdokumenten 2017

Zusammen mit @SeboCode müssen diese durchgeschaut werden. Es muss jeweils entschieden werden, ob das Dokument ins Repo gehört oder nicht.

**Comment by fabianhauser** [comment]
Evtl. könntet ihr dann auch in dem Zug noch https://github.com/openhsr/verein/tree/master/handbuch#buchhaltung ergänzen, der Abschnitt ist noch etwas leer 😄

**Comment by InverseIntegral** [comment]
Wir haben uns entschieden die Dokumente auszudrucken und im Vereinsordner abzulegen.
Ausserdem habe ich die Buchhaltung im Handbuch beschrieben.
