### ISSUE TITLE
LaTeX Workshop HS18

### ISSUE THREAD

**Issue by InverseIntegral** [openhsr/verein#39]
Wie an der GV besprochen, würden wir gerne einen LaTeX Workshop am Anfang des Herbstsemesters 2018 organisieren.

Ich habe vorerst alle Personen, die sich an der GV gemeldet haben, assigned.

**Comment by mattbaumann** [comment]
[LaTeX-Unterlagen Elektrotechnik](https://skripte.hsr.ch/Elektrotechnik/Fachschaft_E/Latex%20Vorlagen/) findet ihr die Vorlagen, die von der Elektrotechnik verwendet werden in Ihrem LaTeX Workshop.

**Comment by dhueppi** [comment]
wurde nicht durchgeführt. bei Bedarf kann Issue wieder geöffnet werden.
