### ISSUE TITLE
Flyer für Studienstart

### ISSUE THREAD

**Issue by fabianhauser** [openhsr/verein#4]
Schreiben eines Studienstart-Guides auf Basis von http://altcomp.raphael.li/start/:
- [ ] Einrichten WLAN
- [ ] Zugriff Webseite
- [ ] Eigenwerbung
- evtl. Sponsoren-Logo

**Comment by raphiz** [comment]
Habe mal geschaut was so Flyer kosten - wenn wir einen A6 Flyer doppelseitig drucken sollten wir 500 Exemplare unter 50 CHF bekommen (Bei flyerking, flyerline oder saxoprint). Alles was grösser ist - oder besseres Druckpapier macht die Sache halt teuer...
Ihr könnt ja auch mal nachschauen - ich finde, der Flyer muss ja nicht vergoldet sein aber Billig sollte er auch nicht wirken...

**Comment by raphiz** [comment]
Nach Rücksprache mit dem Coredump bestellen wir evtl. gleichzeitig mit dem Coredump (Porto)

**Comment by fabianhauser** [comment]
@nikolastankovic ich wiese dir das Issue mal zu, da du anscheinend mit Michi abgemacht hast, dass du den Flyer mal gestaltest?

Wenn wir dir beim Logo oder Flyer irgendwie helfen können, gib doch einfach Bescheid :)

LG Fabian

**Comment by raphiz** [comment]
Habe soeben eine Mail an M. Stolze gesendet mit der Frage, ob wir die Flyer beim Studienbeginn verteilen dürften.

**Comment by nik-sta** [comment]
Hallo Miteinander :) ... Danke für die Arbeit am Flyer :) Ich beginnen jetzt mit dem Design dafür. Könnt ihr mir helfen und schreiben wie ihr euch den Flyer vorgestellt habt`? Und gibt es entsprechend Webseite mit den detaillierteren Informationen?

Cheers, Nikola

**Comment by raphiz** [comment]
Wir können M. Stolze die Flyer geben - dann bekommen alle "Neulinge" eine Kopie 🎉

**Comment by raphiz** [comment]
Zum Inhalt des Flyers: Die neuen Studenten sollten anhand des Flyers:
- vom open\HSR hören
- wissen wer oder was open\HSR ist
- wissen wofür der open\HSR steht bzw. grob was wir machen
- möglichst Mitglied werden (und wissen warum das supertoll ist)
- das WLAN unter Linux einrichten können (falls wir damit den Flyer nicht überladen - btw. es braucht keine Zusatzpakete!)
- wissen wo es weitere Informationen & Anleitungen gibt - speziell [/hilfe](https://www.openhsr.ch/hilfe/) und [/hsr](https://www.openhsr.ch/hsr/) (Überlebensguide)

Zudem soll ein Link zur Website, die E-Mail und 3-4 Logos von Sponsoren (ich glaube 3) drauf ( @fabianhauser wie gross haben wir gesagt?).

Zum Text: Eigentlich haben wir schon alles geschrieben - aber etwas verstreut und nicht sehr kompakt.
Ich habe in openhsr/www.openhsr.ch#39 die Gründe für die Mitgliedschaft aufgeschrieben. Den "Grund" warum es uns gibt ist in den [3 Vereinszielen](https://www.openhsr.ch/community/#verein) festgehalten - und die [WLAN Doku](https://www.openhsr.ch/hsr/wlan/) existiert sowieso.

Ich helfe auch gerne mit beim texten (aber das sollte unbedingt jemand gegenlesen 😉 ) - @nikolastankovic ungehemmt sagen wie und wo ich helfen kann!

Wie mit @nikolastankovic besprochen werden wir einen separaten Branch mit Pull-Request aufmachen wo der aktuelle Stand verfolgt werden kann.

**Comment by michiwieland** [comment]
@nikolastankovic Du findest die Logos der beiden Firmen im Commit 3850d7c

**Comment by raphiz** [comment]
@openhsr/vorstand @nikolastankovic haben wir uns eigentlich auf ein Format festgelegt? A5/A6?
Mit der WLAN Doku ist A5 wohl besser - sonst wäre ich persönlich für A6

**Comment by michiwieland** [comment]
@raphiz, @nikolastankovic  Bezüglich Sponsoren, meine ich, kommen nur die Logos auf den Flyer. Alle 4 Logos sollten gleich gross sein und etwa die Grösse einer Briefmarke haben. (Richtwert) Auf der Homepage fügen wir zusätzlich einen Link auf deren Homepages ein. Die E-Mail lassen wir komplett weg.

**Comment by raphiz** [comment]
Der Flyer ist nun fertig und bei mstolze.
Damit ist diese Aufgabe eigentlich erledigt. @nikolastankovic will noch alles einchecken und kurz dokumentieren - darum lasse ich das Ticket noch offen. 
Ideal wäre es, das bis/am Connect Coding Sprint abschliessen zu können.

**Comment by fabianhauser** [comment]
@nikolastankovic : Könntest du die Ursprungsdateien des Flyer und des Logos noch [in den Pull-Request](https://github.com/openhsr/verein/pull/11) einfügen (oder mir schnell per E-Mail schicken)? Der VSHSR bräuchte die Unterlagen, damit wir auf ihrer Webseite & Unterlagen nicht mehr als alt.comp.hsr geführt werden :wink:

Herzlichen Dank im Voraus!

**Comment by fabianhauser** [comment]
Aktueller Status: Die Logos sind im Repository (siehe auch #11), die Flyer sollten demnächst noch nachgeliefert werden.

**Comment by nik-sta** [comment]
Bitte commit reviewen und mergen :) Dankeschön!

**Comment by fabianhauser** [comment]
Der Flyer wurde dem Repository hinzugefügt :smiley:
