### ISSUE TITLE
Git/GitHub Workshop Swag

### ISSUE THREAD

**Issue by raphiz** [openhsr/verein#43]
Ich habe mal diesen [Git/GitHub Workshop](https://github.com/openhsr/git-github-workshop) geplant/durchgeführt und habe von da noch GitHub Swag übrig. Ich bin nun seit diesem Semester nicht mehr an der HSR und das Material gammelt bei mir so vor sich hin, was ja schade ist... Falls jemand den Kurs durchführen möchte, wäre das Material dort natürlich am besten aufgehoben. Ansonsten könnte man es auch an einem open\HSR Event an alle Interessierten verteilen. Ich würde euch das Material vorbeibringen oder falls niemand Interesse zeigt entsorgen.

Das Swag-Inventar umfasst folgende Dinge, von allem sind ca. 20-30 Stk vorhanden:

- Octocat Stickers
- The Github Flow Booklet
- GitHub Flavoured Markdown
- Git Cheat Sheet
- The Amazing Robopatchers (Comic)

**Comment by The-Compiler** [comment]
Ich nehm mal an, wenn wir wieder nen Git-Workshop machen würden, können wir da auch wieder nach neuem Swag fragen? Ist ja doch schon ne Weile her. Falls ja, wär ich für verteilen :)

**Comment by InverseIntegral** [comment]
Soviel ich weiss, wollte @dotSp0T einen Git-Workshop gegen Ende des Semesters durchführen.

**Comment by dotSp0T** [comment]
Wille ist da, Zeit ist knapp...

**Comment by raphiz** [comment]
OK, dann schalge ich vor, dass ich euch den Swag vorbeibringe. Falls das mit dem Workshop klappt könnt ihr das den Swag dort verteilen, falls nicht an alle die Wollen am nächsten Pizza-Event :pizza: :beer: 
@The-Compiler Das stimmt, man kann für jeden Workshop neuen Swag anfragen. Es kann aber ein paar Wochen dauern bis man von GitHub Antwort bekommt und das auch wirklich Paket eintrifft...

**Comment by fabianhauser** [comment]
Der Swag ist inzwischen bei mir und voraussichtlich werde ich mich am nächsten Workshop beteiligen. Von dem her kann das Issue von mir aus geschlossen werden 🙂

**Comment by RafayelGardishyan** [comment]
> Ich habe mal diesen [Git/GitHub Workshop](https://github.com/openhsr/git-github-workshop) geplant/durchgeführt und habe von da noch GitHub Swag übrig. Ich bin nun seit diesem Semester nicht mehr an der HSR und das Material gammelt bei mir so vor sich hin, was ja schade ist... Falls jemand den Kurs durchführen möchte, wäre das Material dort natürlich am besten aufgehoben. Ansonsten könnte man es auch an einem open\HSR Event an alle Interessierten verteilen. Ich würde euch das Material vorbeibringen oder falls niemand Interesse zeigt entsorgen.
> 
> Das Swag-Inventar umfasst folgende Dinge, von allem sind ca. 20-30 Stk vorhanden:
> 
> * Octocat Stickers
> * The Github Flow Booklet
> * GitHub Flavoured Markdown
> * Git Cheat Sheet
> * The Amazing Robopatchers (Comic)

Hey, I have 22 of The Amazing Robopatchers, you can have them for 10 euro
