### ISSUE TITLE
Flyer 2019

### ISSUE THREAD

**Issue by fabianhauser** [openhsr/verein#47]
- [x] ~Aktualisieren der Sponsoren (sobald bekannt)~ machen wir erst beim 2020er Flyer, da wir sonst nicht rechzeitig für's Verteilen in den Druck gehen können.
- [x] Neuer Inhalt / evtl. Layout:
  - [x] Ausgerichtet auf die Abgabe an neu eingetretene Studierende
  - [x] Verweis auf Anleitungen für Linux / macOS
  - [x] Verweis Studentenportal
  - [x] Kostenlose Vereinsmitgliedschaft
- [x] Druck
  - evtl. nicht mehr so hochwertigen Druck wie auch schon, dafür etwas günstiger.
- [x] Abgabe an Hochschuldienste abklären
  - Bis 2019-07-22 am Empfang Hochschuldienste abgeben

**Comment by The-Compiler** [comment]
Ich kann [Flyeralarm](https://www.flyeralarm.com/ch/content/index/open/id/20142/flyer.html) empfehlen - ich hab bisher nur Aufkleber bestellt, aber sie sind sehr günstig, und haben einen Standort in Zürich (Zwischen HB und Stauffacher) wo man sich beraten lassen kann.

Ich habe auch noch ein Sample-Set von den verschiedenen Papier-/Druckarten von denen, kann das mal mitbringen, wenn das wer genauer anschauen will.

**Comment by fabianhauser** [comment]
@dhueppi hattest du schon Zeit, etwas wegen dem Flyer anzuschauen? 🙂

**Comment by dhueppi** [comment]
ja ich habe mir schon einige Gedanken gemacht und eine erste Skizze gefertigt. Sobald diese Vorzeigebereit ist gebe ich diese durch.

Gruss

Dominic

**Comment by fabianhauser** [comment]
Super, wenn ich was helfen kann, gib Bescheid :)

**Comment by fabianhauser** [comment]
Habe den aktuellen Flyer mal etwas ergänzt - siehe Branch [flyer2019](https://github.com/openhsr/verein/tree/flyer2019). Evtl. wäre es noch eine gute Idee, den Flyer in Inkscape umzusetzen und einen Verschnittrand hinzuzufügen, damit wir ein beim Druck etwas Spielraum haben.

**Comment by fabianhauser** [comment]
Eine weitere Idee wäre es, auf der Rückseite eine Kurzfassung vom [Überlebensguide](https://www.openhsr.ch/hsr/) abzudrucken.

**Comment by fabianhauser** [comment]
Ich habe den Flyer gedruckt, zugeschnitten und am Empfang zur abgabe an die neuen Studierenden abgegeben.
