### ISSUE TITLE
Neues Sponsorenkonzept 2019

### ISSUE THREAD

**Issue by fabianhauser** [openhsr/verein#48]
- Neu gehört das Studentenportal zum open\HSR, dort können auch Logos platziert werden
  - [x] Abklären Besuchszahlen Studentenportal
- Flyer geht neu an sämtliche neu-eingetretenen Studierenden der HSR

Momentan sind wir out-of-sync mit dem Budget und dem Einkommenszeitpunkt vom Sponsoring. Vermutlich wurde das Geld von diesem Jahr bereits im letztjährigen Budget mit eingerechnet.

**Comment by fabianhauser** [comment]
Vorschlag:

| Stufe | Betrag | Leistungen |
|---|---|---|
| Supporter | 600 | 1 Logo auf open\HSR Webseite |
| Sponsor | 1300 | 1 Logo auf open\HSR Webseite und Studentenportal |
| Hauptsponsor | 2000 | 1 Logo auf open\HSR Flyer, Website und Studentenportal, Aufhängen an Events

**Comment by fabianhauser** [comment]
@openhsr/vorstand seid ihr mit dem Vorschlag den neuen Sponsoren-Kategorien & Preisen einverstanden?

**Comment by Scraylex** [comment]
Sieht an und fuer sich ganz gut aus. Vielleicht koennten wir die Staffelung ein wenig hoeher ansetzten so bei 800 und ich wuerde die Supporter nicht direkt auf die open\HSR Webseite sondern erst auf die Flyer und bei events aufhaengen und ab Sponsor-level auf die Webseiten tun.

**Comment by dhueppi** [comment]
Nein, ich finde nur der Hauptsponsor gehört auf den Flyer. Wenn Sponsoren abspringen/wechseln braucht es Anpassungen am Flyer. Wir möchten den neuen Flyer möglichst lange aus Kostengründen nicht verändern. Ich fände es ausserdem noch gut eine sehr günstige Option (ca. 50.- oder 100.-) anzubieten. Man könnte auf der open\HSR Webseite einen "Kachelbereich" für "Friends" anbieten (zB. je 32x32 Pixel Icon). Eventuell auch nur den Vor/Nachnamen dieses "Freundes" anzeigen lassen... Vielleicht lassen sich dadurch Studienabgänger ins Boot holen...

**Comment by dhueppi** [comment]
einen Bereich wie: http://www.milliondollarhomepage.com/

**Comment by fabianhauser** [comment]
@Scraylex Genau, das war die Idee mit dem Flyer: Nur Hauptsponsoren, in der Hoffnung, dass wir den nicht jedes Jahr neu drucken müssen. Den Supporter-Beitrag würde ich gern nicht weiter erhöhen, damit es auch eine tiefere "Einstiegsoption" gibt. Die anderen Angebote sind vom Marketing/Publikumsgrösse vermutlich interessanter für Firmen. (Die Kategorien sind auch nach Publikumsgrösse ausgelegt.)

@dhueppi interessante Idee. Ich denke, dass eine Namensliste in unserem Fall besser geeignet ist (bei Icons ist das Risiko da, dass wir Inhalte zensieren müssten, das möchte ich gerne vermeiden. Evtl. wäre das aber noch eine spannende Idee für den VSHSR?)

Wir könnten eine Kategorie "Gönner" einführen:

| Stufe | Betrag | Leistungen |
|---|---|---|
| Gönner | einmalig 100 | Nur für Vereinsmitglieder: Auflistung auf einer "Gönner" Seite mit Link zur persönlichen Webseite |

Das wäre dann quasi ein einmaliger Gönnerbeitrag mit dauerhaftem Dank. Was haltet ihr davon?

**Comment by fabianhauser** [comment]
Unter https://github.com/openhsr/verein/blob/master/sponsoring/README.md habe ich mal die Sponsoring-Bedingungen aufgeschrieben, damit wir das so den Sponsoren geben können. 
Habt ihr @openhsr/vorstand @das-g noch Ideen wie man das verbessern könnte?

(Den "Gönner" habe ich jetzt erstmal weggelassen.)

**Comment by fabianhauser** [comment]
Ich habe unsere Sponsoren mit dem neuen Konzept angeschrieben.

**Comment by das-g** [comment]
> Das wäre dann quasi ein einmaliger Gönnerbeitrag mit dauerhaftem Dank. Was haltet ihr davon?

Dauerhafte Verpflichtungen (insbesondere als Gegenleistung für einmalige Beiträge) halte ich für problematisch, da der Verein dadurch an Flexibilität verliert.
