### ISSUE TITLE
Rundmail HSR nach Relaunch

### ISSUE THREAD

**Issue by fabianhauser** [openhsr/verein#5]
Nach der GV ( #1 #3 und falls Rebranding, #2) Rundmail an alle HSR-Studenten (& Dozenten/HSR-Staff?) mit Informationen zum Verein.
## Tasks
- [ ] `alt.comp.hsr` am Rande erwähnen (für die bestehenden Studierenden)
- [ ] Versand mit Studierendenvertretung koordinieren
## Newsletter

> Alle  2-3 Monate wollen wir die Mitglieder über Neuigkeiten betr. Open Source an der HSR und dem open\HSR per Newsletter informieren

Gemäss #15

**Comment by fabianhauser** [comment]
An der GV vom Mo, 23.5.16 wurde entschieden, den Newsletter erst nach dem Semesterstart im HS16 zu versenden.

**Comment by fabianhauser** [comment]
@raphiz Wollen wir für den Newsletter ein eigenes Git-Repo machen? Dann könnten wir dort Ideen / Entwürfe in einem Wiki (oder direkt in einem Repository) lagern.

**Comment by raphiz** [comment]
@fabianhauser -> https://github.com/openhsr/newsletter

**Comment by fabianhauser** [comment]
Issue ist neu in https://github.com/openhsr/newsletter/issues/1 festgehalten.
