### ISSUE TITLE
Neuer Vorstand nach GV 19/20

### ISSUE THREAD

**Issue by fabianhauser** [openhsr/verein#51]
- [x] Vorstand auf der Website anpassen
- [x] Vorstand (@openhsr/vorstand) / Organisations Mitglieder / Admins auf GitHub anpassen
- [x] Vorstandsmitglieder im Pass-Repository hinzufügen / entfernen
- [x] Zugriff auf E-Mail Postfach für neue Vorstandsmitglieder einrichten
- [x] Papierunterlagen (Protokolle, Stickers etc.) übergeben (Präsident)
   - Übergabe Ordner an Kassier
- [x] Konto übergeben (neuer Kassier und Präsident)
  - Benötigt das unterschriebene Protokoll der letzten GV.
- [x] Neue Passwörter generieren & Keys updaten
- [x] Vereinspostfach beim VSHSR im Gebäude 4 zeigen
- [x] Evtl. Kontakte/Sponsoren informieren
- [x] Evtl. Verträge anpassen

**Comment by FunkyFabe** [comment]
pub rsa4096 2019-11-08 [SC] [expires: 2022-11-07]
B45B0F2CDA3FAB44C4E58CCB52DDF436BD5E8D0E
uid fabiangermann <germann.fabian@outlook.com>

**Comment by fabianhauser** [comment]
@FunkyFabe: Könntest du mir noch den Vollständigen Public-Key zusenden? Diesen kannst du mit `gpg2 --export --armour > pubkey.asc` exportieren. Merci!

**Comment by FunkyFabe** [comment]
[pubkey.txt](https://github.com/openhsr/verein/files/3837475/pubkey.txt)

Musste für den Upload die Dateierweiterung von .asc auf .txt ändern.

**Comment by fabianhauser** [comment]
@FunkyFabe super, jetzt hast du auch Zugriff 👍 

Falls du noch hilfe benötigst beim einrichten vom E-Mail Postfach, gib Bescheid :)
