### ISSUE TITLE
Aus HSR wird OST

### ISSUE THREAD

**Issue by LiohMoeller** [openhsr/verein#57]
Was ist der Plan? Wird es eine Migration geben? openOST oder so etwas?

**Comment by FunkyFabe** [comment]
Aktueller Stand ist, dass noch vieles ungewiss ist (siehe [Protokoll 2019](https://github.com/openhsr/verein/tree/master/protokolle/2019)). Wir sind daher für alle Vorschläge und Anmerkungen offen. 

 Eine Namensänderung zu "openOST" würde bedeuten, dass wir in Zukunft standortübergreifend (Rapperswil, St. Gallen, Buchs) organisiert wären.

**Comment by LiohMoeller** [comment]
Danke für den Link und das update. Es scheint bereits eine entsprechende issue dazu zu geben. https://github.com/openhsr/verein/issues/49

Ich schliesse diese nun als Duplicate.
