### ISSUE TITLE
Flyer "Quickstart-Guide für Linux und macOS an der Ost" für HS2021 überarbeiten

### ISSUE THREAD

**Issue by das-g** [openhsr/verein#65]
Bisheriger Flyer (vom HS2020, #61): https://github.com/openhsr/verein/tree/master/design/flyers/quickstart-ost

Deadline, damit die neue Version vom Studiengang an die neu-eintretenden Studierenden verteilt werden kann: **Mittwoch 2021-06-30**

### Zu ändern:
- [x] :grey_question: Vereins-Logo (da da noch "open\HSR" drin steht)
- [x] "OST" anstatt "Ost"
- [x] "open\OST" anstatt "open\HSR"
- [x] `openost.ch` anstatt `(www.)openhsr.ch`
- [x] :grey_question: auf Anleitungen auf wiki.ost.ch anstatt auf die (veralteten) auf openost.ch verweisen? Siehe Kommentare unten:
    - https://github.com/openhsr/verein/issues/65#issuecomment-867654566
    - https://github.com/openhsr/verein/issues/65#issuecomment-867709877
 - VPN:
    - [x] `vpn.ost.ch` anstatt `vpn.hsr.ch` verwenden
    - [x] Authenticator anstatt SwivelSecure für 2. Faktor

### Prüfen, ob aktuell:
- [x] WLAN-Angaben
- [x] Passwortwechsel-Link
- [ ] Profil-Link
- [x] VPN-Anleitung Ubuntu
- [x] VPN-Anleitung macOS

---

<details><summary>Kontext</summary>

Die Studiengangssekretärin [Informatik](https://www.ost.ch/i) hat @sfkeller (Head @IFS-HSR) angefragt, diesen Info-Flyer überarbeiten zu lassen, wohl da @sfkeller das ursprüngliche Blatt angeregt hatte und @fabianhauser (damals IFS-Mitarbeiter) dieses damals fürs HS2020 umgesetzt hat. @sfkeller hat wiederum mich (@das-g) gebeten, die Überarbeitung fürs HS2021 mit dem Verein open\OST zu koordinieren, wozu nun dieses Issue dienen soll.

</details>

**Comment by das-g** [comment]
WLAN-Angaben funktionieren so noch.

**Comment by fabianhauser** [comment]
@FunkyFabe `www.openost.ch` sowie `openhsr.ch` und `www.openhsr.ch` sind zur Zeit kaputt, könntest du dafür ein redirect einrichten?

**Comment by fabianhauser** [comment]
Der Verweis auf https://openost.ch für weitere Dokus ist natürlich ein Witz, die sind fast alle veraltet... Es wäre wohl besser, einen entsprechenden Verweis auf die entsprechenden Seite im Confluence unterzubringen. Evtl. könnte man die Links auf openost auch gleich ins Confluence machen?

Evtl. könnte auch noch der IFS-Brand auf dem Blatt untergebracht werden, wenn das IFS den Flyer wieder organisiert?

**Comment by das-g** [comment]
Beim Profil-Anpassen-Link bin ich nicht sicher, ob es besser https://ostch-my.sharepoint.com/person.aspx anstatt https://portal.office.com/ sein sollte.

Wenn ich https://portal.office.com/ gehe, werde ich jedenfalls auf https://www.office.com weitergeleitet. Wenn ich dort dann auf Profilbild oben rechts klicke zeigt der "Mein Office-Profil"-Link auf https://ostch-my.sharepoint.com/person.aspx. Das leitet zwar auf eine weitere URL weiter, die könnte aber Benutzer-spezifisch sein. Dort kann man dann die Profil-Angaben (inkl. Profilbild) ändern / angeben, die nicht fix vom System vorgegeben sind.

(Logisch wäre ja eigentlich https://myaccount.microsoft.com/, worauf auch der "Konto Anzeigen"-Link zeigt, der ebenfalls beim Klick auf das Profilbild oben rechts eingeblendet wird. Dort scheinen allerdings keine Profil-Angaben änderbar zu sein. Wahrscheinlich würde das nur für welche geben, die bei der OST fest vom System vorgegeben sind.)

**Comment by das-g** [comment]
> Der Verweis auf https://openost.ch für weitere Dokus ist natürlich ein Witz, die sind fast alle veraltet... Es wäre wohl besser, einen entsprechenden Verweis auf die entsprechenden Seite im Confluence unterzubringen.

Guter Punkt. Das betrifft den Abschnitt
> ### Und Mehr...
> Weitere   Anleitungen  sowie  Tipps   &   Tricksfindest du unter https://www.openhsr.ch/!

Den Hinweis auf Vereinsmitgliedschaft und openhsr.ch/community weiter unten hingenen würde ich drin lassen.

> Evtl. könnte auch noch der IFS-Brand auf dem Blatt untergebracht werden, wenn das IFS den Flyer wieder organisiert?

@sfkeller Ist das gewünscht? Ich nehme nicht an, dass das IFS (absichtlich oder versehentlich) zur Anlaufstelle für alle OST-Linux( und Mac)-Support-Fragen werden will.

**Comment by das-g** [comment]
> Der Verweis auf https://openost.ch für weitere Dokus ist natürlich ein Witz, die sind fast alle veraltet... Es wäre wohl besser, einen entsprechenden Verweis auf die entsprechenden Seite im Confluence unterzubringen.

Guter Punkt. Das betrifft den Abschnitt
> ### Und Mehr...
> Weitere   Anleitungen  sowie  Tipps   &   Tricks findest du unter https://www.openhsr.ch/!

(Den Hinweis auf Vereinsmitgliedschaft und openhsr.ch/community weiter unten hingegen würde ich drin lassen.)

@LiohMoeller Was wäre der geeignetste Einstiegspunkt, den man da angeben sollte? https://wiki.ost.ch/display/public/IOW/Linux, das nun ja OST-intern allgemein zugänglich ist, wie du in https://github.com/openhsr/verein/issues/61#issuecomment-867620598 bestätigt hast?

**Comment by das-g** [comment]
> Evtl. könnte auch noch der IFS-Brand auf dem Blatt untergebracht werden, wenn das IFS den Flyer wieder organisiert?

@sfkeller Ist das gewünscht? Ich nehme nicht an, dass das IFS (absichtlich oder versehentlich) zur Anlaufstelle für alle OST-Linux( und Mac)-Support-Fragen werden will. Der open\OST eignet sich da sicher besser als Ergänzung zu dem, was die IT der OST inzwischen anbietet.

**Comment by das-g** [comment]
Cisco Anyconnect funktioniert laut @misto auf macOS nach wie vor.

Er schreibt:
>Vielleicht als Ergänzung zum E-Mail, unter macOS kann man auch die Apple Applikationen für Mail, Kalender und so nehmen, muss also nicht Outlook sein.
>
> SwivelSecure stimmt auch nicht mehr, es ist ja jetzt der Authenticator von Microsoft, bzw. man könnte auch noch andere nehmen.

**Comment by das-g** [comment]
Habe in https://github.com/das-g/openhsr-verein/tree/quickstart-guide-hs2021 'mal mit den Anpassungen begonnen.
