### ISSUE TITLE
Übernahme Vereinskonto

### ISSUE THREAD

**Issue by fabianhauser** [openhsr/verein#9]
Vereinskonto übernehmen (vermutlich bei der Bank Linth). Siehe auch [Protokoll GV 2016-05](https://github.com/altcomphsr/verein/blob/master/protokolle/2016/05_generalversammlung/protokoll.md#%C3%9Cbernahme-des-vereinkontos) und #1.

**Comment by fabianhauser** [comment]
@murieleTrentini : Ich werde bei Gelegenheit nochmal Danilo (den ehemaligen Präsidenten) ansprechen, um noch etwas mehr Informationen zu unseren Vorgängern herauszufinden :wink:

Danach machen wir am besten mal einen Termin auf der Bank Linth ab.

**Comment by murieletrentini** [comment]
Denke wir brauchen im Mindesten etwas schriftliches/handfestes das wir der Bank vorlegen können. Quasi eine "Vollmacht".

**Comment by fabianhauser** [comment]
Habe heute noch mit der Bank Linth telefoniert; sie konnten das Konto auf Anhieb nicht finden. Wir sollen spontan (wird vermutlich Freitag Morgen) vorbei kommen und folgendes mitbringen:
- [x] Das unterschriebene GV-Protokoll
- [x] Die unterschriebenen Statuten
- [x] Unsere Ausweise

Falls wir das Konto nicht kriegen: Sollen wir ein neues aufmachen @openhsr/vorstand? Die [Bank Linth hat ungefähr die gleichen](https://www.banklinth.ch/de/privatkunden/konten-karten/privatkonto/vereinskonto) Konditionen [wie die SGKB](https://www.sgkb.ch/de/privatkunden/vereinskonto).

**Comment by fabianhauser** [comment]
Wir waren heute auf der Bank; sie konnten kein Konto vom alt.comp.hsr finden. Sie klären intern aber noch ab, ob jemand was weiss und melden sich nächste Woche noch mal.

Falls die Bank Linth kein Konto von uns hat, würden wir vorschlagen, bei der SGKB ein Konto zu eröffnen.  Das "Online-Banking" der Bank Linth gibt es nämlich [nur für Windows und Mac OS X (aber auch nur wenn man bereit ist, die Paketsignatur zu ignorieren)](https://www.banklinth.ch/de/privatkunden/online-angebote/online-banking/download)...

**Comment by fabianhauser** [comment]
Die Bank Linth konnte leider kein Konto vom alt.comp.hsr finden...

Wir haben deshalb heute gleich ein Konto bei der SGKB eröffnet; Zeichnungsberechtigt ist jeweils der Präsident und die Kassierin (einzeln). Falls wir das noch anpassen wollen, können wir das auch später noch machen.

Die Konto-E-Mails werden an unser Postfach gesendet; Zugang zum E-Banking und Maestro-Karte kriegt @murieleTrentini, ich würde vorschlagen, das jeweils nur die Kassierin direkten Zugriff darauf hat (das Geld reicht zwar eh nicht, um sich in die Karibik abzusetzen :wink:)

@michiwieland wir senden dir die Kontonummer, sobald die Unterlagen nächste Woche angekommen sind.
Wollen wir die Kontonummer / Anschrift auch gleich auf der Webseite publizieren (zwecks Spenden und als Dokumentation)?

**Comment by raphiz** [comment]
> Wollen wir die Kontonummer / Anschrift auch gleich auf der Webseite publizieren (zwecks Spenden und als Dokumentation)?

Jup, spricht ja nichts dagegen, oder?

**Comment by murieletrentini** [comment]
Frau Tomaschett von der SGKB hat angerufen. Offenbar hat sie sich bzgl Maestro Karte geirrt. Die Karte ist beim Vereinskonto nicht inbegriffen und kostet 30.-/Jahr.

Ich finde die Karte für uns nicht unbedingt notwendig. Was meint ihr?

**Comment by raphiz** [comment]
@murieletrentini Nein, von mir aus nicht. Ich bin wenn möglich gegen fixe jährliche Kosten um unseren Nachfolgern keine Steine in den Weg zu legen...

**Comment by fabianhauser** [comment]
Das Konto wurde inzwischen erfolgreich eröffnet. Ich habe die Kontoangaben noch auf der Webseite hinzugefügt (siehe https://github.com/openhsr/www.openhsr.ch/issues/38).

@murieletrentini : Könntest du noch Benachrichtigungen per E-Mail für alle Transaktionen an unser Postfach einrichten? Wäre peinlich, wenn wir z.B. was gespendet kriegen, das aber nicht merken... :)

**Comment by raphiz** [comment]
E-Mail Benachrichtigungen sind gemäss #38 an - also mache ich das Ticket zu!
